#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› brew bundle -verbose"
brew bundle

# Make sure all install.sh scripts are executable
find . -name install.sh -exec chmod +x {} \;

# Find the installers and run them iteratively
find . -name install.sh | while read installer; do
    "${installer}"
done
